env:
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: xterm-256color

# Make background slightly transparent
window.opacity: 1

cursor:
  # Block Underline or Beam
  style: Beam

font:
  normal:
    # Needs to be powerline font if using zsh theme with powerline
    family: Iosevka Nerd Font 
  # Font size
  size: 10

# Colors:
#   primary:
#     background: '#282a36'
#     foreground: '#f8f8f2'
#     bright_foreground: '#ffffff'
#   cursor:
#     text: CellBackground
#     cursor: CellForeground
#   vi_mode_cursor:
#     text: CellBackground
#     cursor: CellForeground
#   search:
#     matches:
#       foreground: '#44475a'
#       background: '#50fa7b'
#     focused_match:
#       foreground: '#44475a'
#       background: '#ffb86c'
#     bar:
#       background: '#282a36'
#       foreground: '#f8f8f2'
#   hints:
#     start:
#       foreground: '#282a36'
#       background: '#f1fa8c'
#     end:
#       foreground: '#f1fa8c'
#       background: '#282a36'
#   line_indicator:
#     foreground: None
#     background: None
#   selection:
#     text: CellForeground
#     background: '#44475a'
#   normal:
#     black: '#21222c'
#     red: '#ff5555'
#     green: '#50fa7b'
#     yellow: '#f1fa8c'
#     blue: '#bd93f9'
#     magenta: '#ff79c6'
#     cyan: '#8be9fd'
#     white: '#f8f8f2'
#   bright:
#     black: '#6272a4'
#     red: '#ff6e6e'
#     green: '#69ff94'
#     yellow: '#ffffa5'
#     blue: '#d6acff'
#     magenta: '#ff92df'
#     cyan: '#a4ffff'
#     white: '#ffffff'


 # Catppuccin!
colors:
  # Default colors
  primary:
    background: '0x1a1b26'
    foreground: '0xc0caf5'

  # Normal colors
  normal:
    black:   '0x15161E'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan:    '0x7dcfff'
    white:   '0xa9b1d6'

  # Bright colors
  bright:
    black:   '0x414868'
    red:     '0xf7768e'
    green:   '0x9ece6a'
    yellow:  '0xe0af68'
    blue:    '0x7aa2f7'
    magenta: '0xbb9af7'
    cyan:    '0x7dcfff'
    white:   '0xc0caf5'

selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When true, selected text will be copied to the primary clipboard
  save_to_clipboard: true

shell:
  program: /bin/sh
  args:
    - -l
    - -c
    - "fish"
