# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "sata_sil24" "vfio_pci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/653518b3-3bca-4f1c-b3a2-6ea214df03ed";
      fsType = "btrfs";
      options = [ "subvol=nixos" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A260-02A7";
      fsType = "vfat";
    };

  fileSystems."/DATA_2" =
    { device = "/dev/disk/by-uuid/15b0e567-5b49-4775-801f-c724d0e478ff";
      fsType = "ext4";
    };

  #fileSystems."/DATA_1" =
  #  { device = "/dev/sdf1";
  #    fsType = "ext4";
  #  };

  fileSystems."/DATA_M2" =
    { device = "/dev/disk/by-uuid/66acef72-51c3-4f45-b06f-48bf5583262a";
      fsType = "ext4";
    };

  swapDevices = [ ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
